server:
  port: 8080
  servlet:
    context-path: /diancan
  error:
    include-stacktrace: always
    #当发生错误时总是在响应中包含堆栈跟踪信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/diancan?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      #在每次连接被创建时执行该SQL语句，用于设置连接的字符集为utf8mb4
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

